### ISSUE TITLE
Doesn't longer work

### ISSUE THREAD

**Issue by Saphyel** [caarlos0/selenium-grid-on-docker-example#1]
Hello I'm following your tutorial but the node-* images doesn't longer alive more than 1sec ... I think selenium or docker changed something or maybe I'm missing something?

**Comment by caarlos0** [comment]
Working as expected here:

![image](https://cloud.githubusercontent.com/assets/245435/20862457/51135b70-b992-11e6-9089-2f971e69c16b.png)

What does the logs say?
